spring:
  profiles:
    active: oauth2
  application:
    name: likelion-security
  security:
    user:
      password: likelion
      name: likelion
      roles: USER

server:
  port: 8085
  servlet:
    session:
      timeout: 10m
      cookie:
        name: JSESSIONID


secret-key: likelion-backend-plus-4th-process-1st-project-secretkey
logging:
  level:
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
      base-path: /actuator
  endpoint:
    prometheus:
      access: read_only

  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: spring
    distribution:
      percentiles-histogram:
        http.server.requests: true