
spring:
  application:
    name: likelion-security
  security:
    user:
      password: likelion
      name: likelion
      roles: USER
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  thymeleaf:
    cache: false
server:
  servlet:
    session:
      timeout: 10m
      cookie:
        name: JSESSIONID
  port: 8085
logging:
  level:
    org.springframework.security: debug


secret-key: likelion-backend-plus-4th-process-1st-project-secretkey